### ISSUE TITLE
Requirements for the Local Visibility app

### ISSUE THREAD

**Issue by JoeyBB91** [ConnectWeather/LocalVisibility#1]
The graphical display for weather conditions is meant only for the employees of Topas Beverages. It is supposed to be a safe environment, secured from external access from outsiders. Here are the desired requirements, as described by the client:
* the graphical display should refresh every 15 seconds;
* once again, the data is supposed to be predictive and there is no interest in retrospective data;
* this means the graph must span over 20 minutes in the future, displaying the predicted weather conditions;
* the graphical application must be **available for mobile systems**, such as smartphones and tablets that run Unix-like operating systems such as iOS or Android, as well as Windows and Blackberry based devices;
* aside from this, the application needs to be accessible through a web-interface;
* the client has requested the service to be in the English language;
* for aesthetics and design, inspiration must be taken from the colors of the Icelandic flag;
* topas Beverages would like their logo to be displayed somewhere gracefully inside the web-interface as well as the application;
* email addresses should function as usernames for this service.

**Comment by koenhendriks** [comment]
I think every bullet point here can be a single issue which would make it clearer for the repo and the people working on it.

**Comment by JoeyBB91** [comment]
This issue has been specified, see other issues.
